version: "3.8"

services:
  app:
    build: .
    container_name: forum_app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: forum_db
    volumes:
      - ./data:/data
    environment:
      SQLITE_DB: /data/my_database.db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
